import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Container } from "react-bootstrap";
import axios from "axios";

import RepoTable from "../components/repoTable";

import { RepoSearchRes, Repo } from "../types";

const amountOfRepos = 100;

interface HomeProps {
  repos: Repo[];
}

export default function Home(props: HomeProps) {
  return (
    <Container>
      <Head>
        <title>Popular repos!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>
          Viser informasjon om topp {amountOfRepos} javascript-repos på github.
        </p>

        <RepoTable repos={props.repos} amountOfReposPerPage={20} />
      </main>
    </Container>
  );
}

export async function getServerSideProps() {
  const repos = await axios.get<RepoSearchRes>(
    `https://api.github.com/search/repositories?q=language:javascript&amp;sort=stars&amp;order=desc&amp;per_page=${amountOfRepos}`
  );

  return {
    props: {
      repos: repos.data.items,
    },
  };
}
